/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GpxMergerRouteImport } from './routes/gpx-merger'
import { Route as IndexRouteImport } from './routes/index'

const GpxMergerRoute = GpxMergerRouteImport.update({
  id: '/gpx-merger',
  path: '/gpx-merger',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gpx-merger': typeof GpxMergerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gpx-merger': typeof GpxMergerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gpx-merger': typeof GpxMergerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gpx-merger'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gpx-merger'
  id: '__root__' | '/' | '/gpx-merger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GpxMergerRoute: typeof GpxMergerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gpx-merger': {
      id: '/gpx-merger'
      path: '/gpx-merger'
      fullPath: '/gpx-merger'
      preLoaderRoute: typeof GpxMergerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GpxMergerRoute: GpxMergerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
